import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link, NavLink, Route, Routes, useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, CalendarDays, ChevronRight, Clock3, Feather, FileSearch, Files, Filter, GitFork, MapPin, Search, ShieldCheck, X } from 'lucide-react';
import { isDemo, repository } from './repository';
import { searchCatalog, type Catalog } from './model';
import Graph from './Graph';
import Detective from './Detective';
import Memory from './Memory';
import { AuthGate, LoginPage, SessionBar } from './Session';
import { DemoTag, Empty, Highlight, Modal, SourceCard } from './ui';

const periods = [{ label: '全部时期', start: 1905, end: 2026 }, { label: '早期岁月', start: 1905, end: 1929 }, { label: '风雨求学', start: 1930, end: 1949 }, { label: '探索与发展', start: 1950, end: 1999 }, { label: '走向未来', start: 2000, end: 2026 }];
const categories = ['全部主题', '学校沿革', '学术教育', '校园生活'];
type OpenRecord = (type: string, id: string) => void;

function Timeline({ catalog, open }: { catalog: Catalog; open: OpenRecord }) {
  const [period, setPeriod] = useState(0); const [category, setCategory] = useState('全部主题'); const [keyword, setKeyword] = useState(''); const [group, setGroup] = useState('year');
  const filtered = catalog.events.filter(e => e.year >= periods[period].start && e.year <= periods[period].end && (category === '全部主题' || e.category === category) && `${e.title}${e.summary}${e.year}`.includes(keyword.trim())).sort((a, b) => a.year - b.year);
  const groups = new Map<string, typeof filtered>();
  filtered.forEach(e => { const key = group === 'decade' ? `${Math.floor(e.year / 10) * 10}年代` : String(e.year); groups.set(key, [...(groups.get(key) || []), e]); });
  const activeFilters = period !== 0 || category !== '全部主题' || keyword !== '';
  return <>
    <section className="intro"><div><div className="eyebrow"><span className="line" />FUDAN MEMORY · DIGITAL ARCHIVE</div><h1>在时间里，<br />读懂我们的<span>复旦。</span></h1><p>循着事件与人物，走进校园的过去。<br />让有出处的历史，与有温度的记忆相遇。</p><a className="intro-link" href="#timeline-start" onClick={e => { e.preventDefault(); document.getElementById('timeline-start')?.scrollIntoView({ behavior: 'smooth' }); }}>开始探索 <ArrowDown size={16} /></a></div><div className="intro-right"><div className="year-line"><span>1905</span><i /><span>2026</span></div><div className="archive-word">记忆有迹<br /><span>来处可寻</span></div><div className="intro-stat"><div><b>{String(catalog.events.length).padStart(2, '0')}</b><span>事件条目</span></div><div><b>{String(catalog.people.length).padStart(2, '0')}</b><span>人物档案</span></div><div><b>{String(catalog.sources.length).padStart(2, '0')}</b><span>资料来源</span></div></div></div></section>
    <div className="timeline-heading" id="timeline-start"><div><span className="eyebrow">CHRONOLOGY</span><h2>校史时间轴</h2></div><div className="segmented" aria-label="时间粒度"><button className={group === 'year' ? 'active' : ''} onClick={() => setGroup('year')}>按年份</button><button className={group === 'decade' ? 'active' : ''} onClick={() => setGroup('decade')}>按十年</button></div></div>
    <div className="timeline-layout"><aside className="period-sidebar"><span className="eyebrow">浏览时期</span><nav aria-label="时期筛选">{periods.map((p, i) => <button className={period === i ? 'selected' : ''} key={p.label} onClick={() => setPeriod(i)}><span>{p.label}<small>{i === 0 ? '1905 — 至今' : `${p.start} — ${p.end}`}</small></span><ChevronRight size={16} /></button>)}</nav><div className="sidebar-note"><BookOpen size={23} strokeWidth={1.3} /><h3>每条记录，都有来处</h3><p>点击事件卡片，查看关联人物与资料出处。不同来源分别保留。</p><Link to="/sources">浏览资料目录 <ArrowUpRight size={14} /></Link></div></aside>
    <section className="timeline-main"><div className="filter-bar"><div className="row"><Filter size={16} /><select aria-label="筛选事件主题" value={category} onChange={e => setCategory(e.target.value)}>{categories.map(c => <option key={c}>{c}</option>)}</select></div><label className="input-icon"><Search size={16} /><input placeholder="在时间轴中查找" aria-label="在时间轴中查找" value={keyword} onChange={e => setKeyword(e.target.value)} /></label></div><div className="results-meta" aria-live="polite"><span>共 {filtered.length} 条记录{isDemo && ' · 当前均为演示资料'}</span>{activeFilters && <button className="text-button" onClick={() => { setPeriod(0); setCategory('全部主题'); setKeyword(''); }}><X size={13} />清除筛选</button>}</div>
      {!filtered.length ? <Empty>没有找到符合条件的事件，试试清除筛选。</Empty> : <div className="timeline">{[...groups].map(([label, events]) => <section className="timeline-group" key={label}><div className="year-marker"><span>{label}</span><i /></div><div className="event-stack">{events.map(e => <button className="event-card" key={e.id} onClick={() => open('event', e.id)}><div className="event-card-top"><span className={`category category-${categories.indexOf(e.category)}`}>{e.category}</span><span className="event-index">NO. {e.id.replace('e', '').padStart(3, '0')}</span></div><h3>{group === 'decade' && <span className="inline-year">{e.year} · </span>}{e.title}</h3><p>{e.summary}</p><div className="event-card-bottom"><span><MapPin size={14} />{e.place}</span><span><Files size={14} />{e.sourceIds.length} 份资料</span><ArrowUpRight className="card-arrow" size={20} /></div></button>)}</div></section>)}</div>}
      <div className="timeline-end"><span />{activeFilters ? '已展示当前筛选的全部记录' : '历史仍在继续，下一段记忆由你写下。'}<Link to="/memories">记录我的记忆 <ArrowRight size={14} /></Link></div>
    </section><aside className="discovery-sidebar"><div className="discovery-card"><span className="eyebrow">ANOTHER PERSPECTIVE</span><GitFork size={36} strokeWidth={1.1} /><h3>从人物出发<br />看见历史的连接</h3><p>师生、同窗、学术合作。沿着关系，发现新的线索。</p><Link className="button" to="/people">探索人物关系 <ArrowUpRight size={17} /></Link></div><div className="reading-note"><span className="eyebrow">阅读提示</span><h3>历史与记忆，<br />分别呈现。</h3><p>史料条目保留来源；个人讲述标注为记忆。它们可以相互参照，也可以保留不同的理解。</p><Link to="/memories">走进记忆共创 <ArrowRight size={15} /></Link></div></aside></div>
  </>;
}

function SearchPage({ catalog, open }: { catalog: Catalog; open: OpenRecord }) {
  const [params, setParams] = useSearchParams(); const query = params.get('q') || ''; const [draft, setDraft] = useState(query); const [type, setType] = useState('all'); const [page, setPage] = useState(1);
  useEffect(() => { setDraft(query); setPage(1); }, [query]);
  const results = useMemo(() => searchCatalog(catalog, query), [catalog, query]);
  const filtered = results.filter(r => type === 'all' || r.type === type); const pages = Math.ceil(filtered.length / 8);
  function search(e: FormEvent) { e.preventDefault(); setParams({ q: draft.trim() }); setPage(1); }
  return <><div className="page-heading"><div><div className="eyebrow">SEARCH THE ARCHIVE</div><h1>寻找一条历史线索<span>全站检索</span></h1><p>从年份、事件、人物或资料开始。多个关键词以空格分隔。</p></div></div><section className="panel search-panel"><form className="large-search" onSubmit={search}><Search size={23} /><input value={draft} onChange={e => setDraft(e.target.value)} aria-label="全站搜索关键词" placeholder="搜索事件、人物、资料…" maxLength={100} /><button className="button primary">搜索</button></form><div className="tabs">{[['all', '全部'], ['event', '事件'], ['person', '人物'], ['source', '史料']].map(([value, label]) => <button className={type === value ? 'active' : ''} key={value} onClick={() => { setType(value); setPage(1); }}>{label} <small>{value === 'all' ? results.length : results.filter(r => r.type === value).length}</small></button>)}</div>{!query.trim() ? <Empty>输入关键词开始查找，例如“校园”“学术”或“江知远”。</Empty> : !filtered.length ? <Empty>没有找到“{query}”，试试更短的关键词。</Empty> : <><p className="small muted" aria-live="polite">找到 {filtered.length} 条相关记录</p>{filtered.slice((page - 1) * 8, page * 8).map(r => <button key={`${r.type}-${r.id}`} className="search-result" onClick={() => open(r.type, r.id)}><span className="tag">{r.label}</span><div><h3><Highlight text={r.title} query={query} /></h3><p><Highlight text={r.summary} query={query} /></p></div><ArrowUpRight size={20} /></button>)}{pages > 1 && <div className="pagination"><button className="button secondary" disabled={page === 1} onClick={() => setPage(p => p - 1)}>上一页</button><span>{page} / {pages}</span><button className="button secondary" disabled={page === pages} onClick={() => setPage(p => p + 1)}>下一页</button></div>}</>}</section></>;
}

function RecordDetail({ catalog, value, open, close }: { catalog: Catalog; value: string; open: OpenRecord; close: () => void }) {
  const [type, id] = value.split(':'); const event = type === 'event' ? catalog.events.find(e => e.id === id) : undefined;
  const person = type === 'person' ? catalog.people.find(p => p.id === id) : undefined; const source = type === 'source' ? catalog.sources.find(s => s.id === id) : undefined;
  const title = event?.title || person?.name || source?.title || '未找到记录';
  const sources = catalog.sources.filter(s => (event?.sourceIds || person?.sourceIds || []).includes(s.id));
  return <Modal title={title} onClose={close}>{(event?.demo || person?.demo || source?.demo) && <p className="notice-strip compact">演示资料 · 内容与人物仅用于界面测试，不作为真实校史依据。</p>}
    {event && <><div className="row wrap muted"><span><CalendarDays size={16} />{event.year}</span><span className="tag">{event.category}</span><span><MapPin size={15} />{event.place}</span></div><p className="detail-lead">{event.summary}</p><p className="preserve">{event.content}</p><h3>关联人物</h3><div className="row wrap">{catalog.people.filter(p => event.personIds.includes(p.id)).map(p => <button className="button secondary small-button" key={p.id} onClick={() => open('person', p.id)}>{p.name}<ArrowUpRight size={14} /></button>)}</div></>}
    {person && <><p className="muted">{person.role} · {person.years}</p><p className="detail-lead">{person.summary}</p><h3>相关事件</h3><div className="related-list">{catalog.events.filter(e => e.personIds.includes(person.id)).map(e => <button key={e.id} onClick={() => open('event', e.id)}><span>{e.title}</span><small>{e.year}</small></button>)}</div><h3>关系与出处</h3>{catalog.relations.filter(r => r.from === id || r.to === id).map(r => <div className="relation-record" key={r.id}><b>{catalog.people.find(p => p.id === r.from)?.name} — {r.type} — {catalog.people.find(p => p.id === r.to)?.name}</b><div>{r.sourceIds.map(sid => <button className="text-button" key={sid} onClick={() => open('source', sid)}>{catalog.sources.find(s => s.id === sid)?.title || sid}<ArrowUpRight size={13} /></button>)}</div></div>)}</>}
    {sources.length > 0 && <><h3>资料与出处</h3>{sources.map(s => <SourceCard key={s.id} source={s} />)}</>}{source && <SourceCard source={source} />}{!event && !person && !source && <Empty>该记录不存在或已下架，请返回列表。</Empty>}
  </Modal>;
}

export default function App() {
  const [catalog, setCatalog] = useState<Catalog | null>(null); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [query, setQuery] = useState('');
  const [params, setParams] = useSearchParams(); const navigate = useNavigate(); const location = useLocation();
  useEffect(() => { let live = true; setError(''); repository.catalog().then(data => { if (live) setCatalog(data); }).catch(e => { if (live) setError(e instanceof Error ? e.message : '加载失败'); }); return () => { live = false; }; }, [retry]);
  useEffect(() => { window.scrollTo({ top: 0 }); }, [location.pathname]);
  const open: OpenRecord = (type, id) => { const next = new URLSearchParams(params); next.set('record', `${type}:${id}`); setParams(next); };
  const close = () => { const next = new URLSearchParams(params); next.delete('record'); setParams(next, { replace: true }); };
  function globalSearch(e: FormEvent) { e.preventDefault(); navigate(`/search?q=${encodeURIComponent(query.trim())}`); }
  return <><a href="#main-content" className="skip-link">跳转到主要内容</a><header className="site-header"><div className="header-inner"><Link className="brand" to="/"><span className="brand-symbol">复</span><span><b>复旦记忆</b><small>校史数字化共创平台</small></span></Link><nav className="main-nav" aria-label="主导航"><NavLink to="/" end><Clock3 size={16} />校史时间轴</NavLink><NavLink to="/people"><GitFork size={16} />人物关系</NavLink><NavLink to="/detectives"><FileSearch size={16} />档案侦探局</NavLink><NavLink to="/sources"><BookOpen size={16} />资料目录</NavLink><NavLink to="/memories"><Feather size={16} />记忆共创</NavLink></nav><form className="header-search" onSubmit={globalSearch}><input aria-label="搜索校史" placeholder="搜索校史…" value={query} maxLength={100} onChange={e => setQuery(e.target.value)} /><button aria-label="提交全站搜索"><Search size={18} /></button></form></div></header><SessionBar />
    {isDemo && <div className="demo-banner"><span className="demo-pill">前端原型</span><span>学生共创项目 · 非校方官方网站 · 事件、人物与史料均为演示内容</span><Link to="/review"><ShieldCheck size={14} />审核演示<ChevronRight size={13} /></Link></div>}
    <main id="main-content" className="main-container">{error ? <div className="error-box" role="alert">{error}<button className="button secondary" onClick={() => setRetry(r => r + 1)}>重新加载</button></div> : !catalog ? <Empty>正在打开档案…</Empty> : <><Routes><Route path="/login" element={<LoginPage />} /><Route path="/" element={<Timeline catalog={catalog} open={open} />} /><Route path="/people" element={<Graph catalog={catalog} open={open} />} /><Route path="/detectives" element={<Detective catalog={catalog} open={open} />} /><Route path="/search" element={<SearchPage catalog={catalog} open={open} />} /><Route path="/sources" element={<><div className="page-heading"><div><div className="eyebrow">SOURCES & REFERENCES</div><h1>让每一条线索，都有出处<span>资料目录</span></h1><p>区分资料类型，保留摘录、登记信息与展示范围。</p></div><span className="count-label">{catalog.sources.length} 份资料</span></div><div className="sources-grid">{catalog.sources.map(s => <SourceCard source={s} key={s.id} />)}</div></>} /><Route path="/memories" element={<AuthGate><Memory key="memories" /></AuthGate>} /><Route path="/review" element={<AuthGate reviewer><Memory key="review" review /></AuthGate>} /><Route path="*" element={<Empty>没有这个页面。<Link to="/">返回时间轴</Link></Empty>} /></Routes>{params.get('record') && <RecordDetail catalog={catalog} value={params.get('record')!} open={open} close={close} />}</> }</main>
    <footer><div><span className="footer-name">复旦记忆</span><span>以史料为起点，以共同记忆为延伸。</span></div><div><Link to="/detectives">档案侦探局</Link><Link to="/sources">资料与出处</Link><Link to="/review">{isDemo ? '审核演示' : '审核工作台'}</Link><span>学生项目 · 2026</span></div></footer>
  </>;
}
